Traceback (most recent call last):
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/tbent/.miniconda3/envs/bie_book/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
A = self_interaction_matrix(double_layer_matrix, topo, qr_topo)
B = double_layer_matrix(fault, qr_fault, topo[0], topo[1])
slip = slip_fnc(qr_fault[0])
v = B.dot(slip)
surf_disp = np.linalg.solve(A - 0.5 * np.eye(A.shape[0]), v)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-24-c0d4982dda4c>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mA[0m [0;34m=[0m [0mself_interaction_matrix[0m[0;34m([0m[0mdouble_layer_matrix[0m[0;34m,[0m [0mtopo[0m[0;34m,[0m [0mqr_topo[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mB[0m [0;34m=[0m [0mdouble_layer_matrix[0m[0;34m([0m[0mfault[0m[0;34m,[0m [0mqr_fault[0m[0;34m,[0m [0mtopo[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mtopo[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mslip[0m [0;34m=[0m [0mslip_fnc[0m[0;34m([0m[0mqr_fault[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mv[0m [0;34m=[0m [0mB[0m[0;34m.[0m[0mdot[0m[0;34m([0m[0mslip[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0msurf_disp[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinalg[0m[0;34m.[0m[0msolve[0m[0;34m([0m[0mA[0m [0;34m-[0m [0;36m0.5[0m [0;34m*[0m [0mnp[0m[0;34m.[0m[0meye[0m[0;34m([0m[0mA[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m,[0m [0mv[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'self_interaction_matrix' is not defined
NameError: name 'self_interaction_matrix' is not defined

